bug: cleaned precommit cache and display log

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,11 +20,17 @@ jobs:
         with:
           python-version: "3.x"
 
+      - name: Clear pre-commit cache
+        run: pre-commit clean
+
       - name: Install pre-commit
         run: pip install pre-commit
 
       - name: Run pre-commit
         run: pre-commit run --all-files --show-diff-on-failure
+
+      - name: Display pre-commit log
+        run: cat /home/runner/.cache/pre-commit/pre-commit.log || echo "Log not found"
 
   tests:
     name: Run Tests
